### ISSUE TITLE
allow running test after DEPOPTS are installed

### ISSUE THREAD

**Issue by edwintorok** [ocaml/ocaml-ci-scripts#144]
Since [this](https://github.com/ocaml/ocaml-ci-scripts/issues/30) got applied and then reverted would it be acceptable to have an env var in `.travis.yml` that allows the user to choose whether they want to run the tests after installing DEPOPTS or not?

**Comment by samoht** [comment]
I am not sure why we are not running the tests after the depopts are installed. I think that would be a good idea to do it if `TEST` is set (e.g. no need to add an other variable I think).

**Comment by edwintorok** [comment]
Do you want this behaviour:
 * `TESTS` is unset: run test only during initial install (current behaviour)
 * `TESTS=true`: run test on both initial install and after installing depopts
 * `TESTS=false`: do not run test at all

**Comment by samoht** [comment]
If I remember correctly, I reverted #30 because opam annoyingly is running the tests for all the installed packages, not the main one (hopefully @AltGr have fixed this in opam2). Ideally you just want to run the test of the top-level package, which is what the `TESTS=1` tries to do (but sometime fails too).

So I am fine to just have:
- `TESTS=true` or unset: run test on both initial install and after installing depopts
- `TESTS=false`: do not run test at all

if the implementation manages to minimize the number of tests run in other packages than the top-level one.

**Comment by edwintorok** [comment]
Thanks, see https://github.com/ocaml/ocaml-ci-scripts/pull/145. It doesn't completely eliminate the problem though, it still has to install/recompile/run the tests of test-only dependencies.

**Comment by AltGr** [comment]
@samoht: yes, it's fixed in opam2, `--test` now only applies to what's listed on the command-line
