### ISSUE TITLE
.travis-docker.sh fails when removing travis-opam

### ISSUE THREAD

**Issue by bbc2** [ocaml/ocaml-ci-scripts#265]
This can be reproduced with:

```dockerfile
FROM ocaml/opam2:alpine
WORKDIR /home/opam/opam-repository
RUN git checkout master
RUN git pull -q origin master
RUN opam remove travis-opam
RUN opam switch 4.06 ||          opam switch create ocaml-base-compiler.4.06
RUN opam update -u -y
RUN opam depext -ui travis-opam
RUN cp ~/.opam/$(opam switch show)/bin/ci-opam ~/
RUN opam remove -a travis-opam
```

This outputs:

```
The following dependencies couldn't be met:
  - ocaml -> ocaml-config
Your request can't be satisfied:
  - Conflicting query for package ocaml-config.1
```

It looks like `ocaml-config` is a recent package and that the `-a` option makes opam try to remove it.

**Comment by seliopou** [comment]
I'm having the same issue [https://travis-ci.org/inhabitedtype/angstrom/jobs/450217665]().

**Comment by NathanReb** [comment]
I ran into the same issue yesterday but it appears to be an opam `--auto-remove` bug rather than an issue with the script itself.

Also note that for some reason, my `4.05`, `4.06` and `4.07` builds are affected but not the `4.04` ones even though the `ocaml-config` package is installed the exact same way and the `ocaml` package depends on it.

**Comment by dra27** [comment]
This is worked around in #268
