### ISSUE TITLE
ocamlformat support

### ISSUE THREAD

**Issue by hannesm** [ocaml/ocaml-ci-scripts#292]
It would be good to integrate ocamlformat into CI scripts to adapt it into more projects, and have a CI job which checks that the submitted PRs conform to the selected style. I'd propose to require the ocamlformat version explicitly `OCAMLFORMAT="0.9"` (avoiding issues like the `latest` for `OCAML_VERSION` which support we phased out over time -- it's utopic to assume all ci-script users will always want the same version of ocamlformat).

I've recently seen [this commit](https://github.com/avsm/duniverse/commit/245cd7dd3f5881cb6cf395f62e5e0540d56d9a21) which contains necessary changes (of course they need to be adapted to the scripts here).

if others think this is a good idea, and someone more familiar with the current code base could implement it, that'd be great! :)

//cc @NathanReb @emillon @avsm @samoht (further discussion also in https://github.com/mirage/ocaml-cstruct/pull/234)

**Comment by NathanReb** [comment]
I'm actually experimenting around this atm. I think a more satisfying way to deal with this would be to check formatting on a separate build.

That would allow us to get the results for this check faster since it doesn't require you to install any dependencies and to actually build or run the test for the project.

You can have a look at [this PR](https://github.com/avsm/duniverse/pull/18) I wrote. The ocamlformat build is separate from the other ones and uses images with pre-installed versions of ocamlformat and dune. Right now they're hosted on my dockerhub but it would be nice to have them on the `ocaml` one.

**Comment by hannesm** [comment]
since I do not use ocaml-ci-scripts any longer, I'll close this.
