### ISSUE TITLE
Using system OCaml compiler in travis-opam

### ISSUE THREAD

**Issue by smimram** [ocaml/ocaml-ci-scripts#310]
Hi,

I am using `travis-opam.sh` to build on travis. Is there a way of using the system compiler instead of building the whole OCaml compiler at each commit? The doc seems to mention that I have to set `OCAML_VERSION` to something...

Thanks!

**Comment by smimram** [comment]
I found out that I could set `OPAM_SWITCH=ocaml-system`, but for some reason OCaml still gets compiled. It seems that dune depends on `ocamlfind-secondary` which depends on `ocaml-secondary-compiler` which ends up compiling an OCaml compiler. For info, I am on Travis' bionic with OCaml 4.05.0 installed on system.

**Comment by hannesm** [comment]
Dear @smimram, the "ocaml-secondary-compiler" / "ocamlfind-secondary" are packages introduced by dune >= 2.0.0 on ocaml < 4.06.0 -- the dune development team decided to drop support for older compilers in their codebase, and introduced these packages to get dune >= 2.0.0 on ocaml < 4.06.0.

I can see three options here: 
- avoid dune >= 2.0.0 in your package universe (may be as easy as defining "dune {< "2.0.0"}" in your opam file;
- upgrade your package to ocaml 4.06.0+;
- accept to bootstrap an OCaml compiler >= 4.06.0 during each CI run.

closing since there's not much ocaml-ci-scripts can do for you.

**Comment by smimram** [comment]
Thanks for your answer! While I understand it from a technical point of view, I still feel bad that most of the users of the ci scripts will end up uselessly heating the planet in order to compile ocaml...

**Comment by hannesm** [comment]
I agree with you, and don't particularly like their solution. You should report this at the ocaml/dune repository rather than here, though -- since it is their responsibility, rather than ocaml-ci-scripts one.
